# Generated by Django 3.2.13 on 2022-06-21 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='alumno',
            fields=[
                ('matricula_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_alumno', models.CharField(max_length=50)),
                ('apellido_alumno', models.CharField(default='', max_length=50)),
                ('carrera_alumno', models.CharField(max_length=50)),
                ('correo_alumno', models.EmailField(max_length=50)),
                ('telefono_alumno', models.CharField(max_length=50)),
                ('created_at_alumno', models.DateTimeField(auto_now_add=True)),
                ('updated_at_alumno', models.DateTimeField(auto_now=True)),
                ('titularse_alumno', models.BooleanField(default=False)),
                ('id_user_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='estadisticasTitulacion',
            fields=[
                ('id_estadisticas_titulacion', models.AutoField(primary_key=True, serialize=False)),
                ('genero_estadisticas_titulacion', models.CharField(max_length=50)),
                ('fecha_init_estadisticas_titulacion', models.DateField()),
                ('fecha_end_estadisticas_titulacion', models.DateField()),
                ('ingreso_estadisticas_titulacion', models.IntegerField()),
                ('egreso_estadisticas_titulacion', models.IntegerField()),
                ('titulados_estadisticas_titulacion', models.IntegerField()),
                ('rezagados_estadisticas_titulacion', models.IntegerField()),
                ('porcentaje_titulados_estadisticas_titulacion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tituloElectronico',
            fields=[
                ('id_titulo_electronico', models.AutoField(primary_key=True, serialize=False)),
                ('foto_infantil_bn_titulo_electronico', models.CharField(max_length=100)),
                ('foto_infantil_color_titulo_electronico', models.CharField(max_length=100)),
                ('curp_titulo_electronico', models.CharField(max_length=50)),
                ('acta_nacimiento_titulo_electronico', models.CharField(max_length=100)),
                ('certificado_bachiller_titulo_electronico', models.CharField(max_length=100)),
                ('tsu_titulo_electronico', models.CharField(max_length=100, null=True)),
                ('status_foto_infantil_bn_titulo_electronico', models.BooleanField(default=False)),
                ('status_foto_infantil_color_titulo_electronico', models.BooleanField(default=False)),
                ('status_curp_titulo_electronico', models.BooleanField(default=False)),
                ('status_acta_nacimiento_titulo_electronico', models.BooleanField(default=False)),
                ('status_certificado_bachiller_titulo_electronico', models.BooleanField(default=False)),
                ('status_tsu_titulo_electronico', models.BooleanField(default=False)),
                ('created_at_titulo_electronico', models.DateTimeField(auto_now_add=True)),
                ('updated_at_titulo_electronico', models.DateTimeField(auto_now=True)),
                ('id_alumno_titulo_electronico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('matricula_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(max_length=50)),
                ('apellido_empleado', models.CharField(max_length=50)),
                ('correo_empleado', models.EmailField(max_length=50)),
                ('telefono_empleado', models.CharField(max_length=50)),
                ('created_at_empleado', models.DateTimeField(auto_now_add=True)),
                ('updated_at_empleado', models.DateTimeField(auto_now=True)),
                ('puesto_empleado', models.CharField(max_length=50)),
                ('nivel_academico_empleado', models.CharField(max_length=50)),
                ('id_user_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='certificadoTitulacion',
            fields=[
                ('id_certificado_titulacion', models.AutoField(primary_key=True, serialize=False)),
                ('plan_estudio_certificado_titulacion', models.CharField(max_length=50)),
                ('periodo_escolar_certificado_titulacion', models.CharField(max_length=50)),
                ('id_alumno_certificado_titulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.alumno')),
            ],
        ),
    ]
