# Generated by Django 3.2.13 on 2022-06-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='titularse_alumno',
        ),
        migrations.AddField(
            model_name='alumno',
            name='estadiasIngLic_alumno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='estadiasTSU_alumno',
            field=models.BooleanField(default=False),
        ),
    ]
