# Generated by Django 3.2.13 on 2022-06-24 00:17

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220622_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificadotitulacion',
            name='periodo_escolar_certificado_titulacion',
        ),
        migrations.AddField(
            model_name='certificadotitulacion',
            name='periodo_escolar_end_certificado_titulacion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='certificadotitulacion',
            name='periodo_escolar_init_certificado_titulacion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='acta_nacimiento_titulo_electronico',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='acta_nacimiento_titulo_electronico'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='certificado_bachiller_titulo_electronico',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='certificado_bachiller_titulo_electronico'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='curp_titulo_electronico',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='curp_titulo_electronico'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='foto_infantil_bn_titulo_electronico',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='foto_infantil_bn_titulo_electronico'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='foto_infantil_color_titulo_electronico',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='foto_infantil_color_titulo_electronico'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='status_acta_nacimiento_titulo_electronico',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='status_certificado_bachiller_titulo_electronico',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='status_curp_titulo_electronico',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='status_foto_infantil_bn_titulo_electronico',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='status_foto_infantil_color_titulo_electronico',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='status_tsu_titulo_electronico',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='tsu_titulo_electronico',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='tsu_titulo_electronico'),
        ),
    ]
