# Generated by Django 3.2.13 on 2022-06-24 21:35

import apps.home.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220623_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tituloelectronico',
            name='acta_nacimiento_titulo_electronico',
            field=apps.home.models.CloudinaryField(max_length=255, verbose_name='acta_nacimiento_titulo_electronico'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='certificado_bachiller_titulo_electronico',
            field=apps.home.models.CloudinaryField(max_length=255, verbose_name='certificado_bachiller_titulo_electronico'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='curp_titulo_electronico',
            field=apps.home.models.CloudinaryField(max_length=255, verbose_name='curp_titulo_electronico'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='foto_infantil_bn_titulo_electronico',
            field=apps.home.models.CloudinaryField(max_length=255, verbose_name='foto_infantil_bn_titulo_electronico'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='foto_infantil_color_titulo_electronico',
            field=apps.home.models.CloudinaryField(max_length=255, verbose_name='foto_infantil_color_titulo_electronico'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='tsu_titulo_electronico',
            field=apps.home.models.CloudinaryField(max_length=255, null=True, verbose_name='tsu_titulo_electronico'),
        ),
    ]
