# Generated by Django 3.2.13 on 2022-06-24 21:39

import apps.home.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220624_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tituloelectronico',
            name='id_alumno_titulo_electronico',
        ),
        migrations.RemoveField(
            model_name='tituloelectronico',
            name='tsu_titulo_electronico_id',
        ),
        migrations.AddField(
            model_name='tituloelectronico',
            name='id_alumno_titulo_electronico_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.alumno'),
        ),
        migrations.AddField(
            model_name='tituloelectronico',
            name='tsu_titulo_electronico',
            field=apps.home.models.CloudinaryField(max_length=255, null=True, verbose_name='tsu_titulo_electronico'),
        ),
    ]
