# Generated by Django 3.2.13 on 2022-06-24 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220624_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tituloelectronico',
            old_name='id_alumno_titulo_electronico_id',
            new_name='id_alumno_titulo_electronico',
        ),
    ]
