# Generated by Django 3.2.13 on 2022-06-24 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220624_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tituloelectronico',
            name='acta_nacimiento_titulo_electronico',
        ),
        migrations.RemoveField(
            model_name='tituloelectronico',
            name='certificado_bachiller_titulo_electronico',
        ),
        migrations.RemoveField(
            model_name='tituloelectronico',
            name='comentarios_acta_nacimiento_titulo_electronico',
        ),
        migrations.RemoveField(
            model_name='tituloelectronico',
            name='comentarios_certificado_bachiller_titulo_electronico',
        ),
        migrations.RemoveField(
            model_name='tituloelectronico',
            name='comentarios_curp_titulo_electronico',
        ),
        migrations.RemoveField(
            model_name='tituloelectronico',
            name='comentarios_foto_infantil_bn_titulo_electronico',
        ),
        migrations.RemoveField(
            model_name='tituloelectronico',
            name='comentarios_foto_infantil_color_titulo_electronico',
        ),
        migrations.RemoveField(
            model_name='tituloelectronico',
            name='comentarios_tsu_titulo_electronico',
        ),
        migrations.RemoveField(
            model_name='tituloelectronico',
            name='created_at_titulo_electronico',
        ),
        migrations.RemoveField(
            model_name='tituloelectronico',
            name='curp_titulo_electronico',
        ),
        migrations.RemoveField(
            model_name='tituloelectronico',
            name='foto_infantil_bn_titulo_electronico',
        ),
        migrations.RemoveField(
            model_name='tituloelectronico',
            name='foto_infantil_color_titulo_electronico',
        ),
        migrations.RemoveField(
            model_name='tituloelectronico',
            name='id_alumno_titulo_electronico',
        ),
        migrations.RemoveField(
            model_name='tituloelectronico',
            name='status_acta_nacimiento_titulo_electronico',
        ),
        migrations.RemoveField(
            model_name='tituloelectronico',
            name='status_certificado_bachiller_titulo_electronico',
        ),
        migrations.RemoveField(
            model_name='tituloelectronico',
            name='status_curp_titulo_electronico',
        ),
        migrations.RemoveField(
            model_name='tituloelectronico',
            name='status_foto_infantil_bn_titulo_electronico',
        ),
        migrations.RemoveField(
            model_name='tituloelectronico',
            name='status_foto_infantil_color_titulo_electronico',
        ),
        migrations.RemoveField(
            model_name='tituloelectronico',
            name='status_tsu_titulo_electronico',
        ),
        migrations.RemoveField(
            model_name='tituloelectronico',
            name='tsu_titulo_electronico',
        ),
        migrations.RemoveField(
            model_name='tituloelectronico',
            name='updated_at_titulo_electronico',
        ),
    ]
