# Generated by Django 3.2.13 on 2022-06-24 23:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20220624_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='tituloelectronico',
            name='acta_nacimiento_titulo_electronico',
            field=models.ImageField(null=True, upload_to='files/', verbose_name='Acta de Nacimiento'),
        ),
        migrations.AddField(
            model_name='tituloelectronico',
            name='certificado_bachiller_titulo_electronico',
            field=models.ImageField(null=True, upload_to='files/', verbose_name='Certificado de Bachiller'),
        ),
        migrations.AddField(
            model_name='tituloelectronico',
            name='comentarios_acta_nacimiento_titulo_electronico',
            field=models.TextField(null=True, verbose_name='Comentarios Acta de Nacimiento'),
        ),
        migrations.AddField(
            model_name='tituloelectronico',
            name='comentarios_certificado_bachiller_titulo_electronico',
            field=models.TextField(null=True, verbose_name='Comentarios Certificado de Bachiller'),
        ),
        migrations.AddField(
            model_name='tituloelectronico',
            name='comentarios_curp_titulo_electronico',
            field=models.TextField(null=True, verbose_name='Comentarios CURP'),
        ),
        migrations.AddField(
            model_name='tituloelectronico',
            name='comentarios_foto_infantil_bn_titulo_electronico',
            field=models.TextField(null=True, verbose_name='Comentarios Foto Infantil B/N'),
        ),
        migrations.AddField(
            model_name='tituloelectronico',
            name='comentarios_foto_infantil_color_titulo_electronico',
            field=models.TextField(null=True, verbose_name='Comentarios Foto Infantil Color'),
        ),
        migrations.AddField(
            model_name='tituloelectronico',
            name='comentarios_tsu_titulo_electronico',
            field=models.TextField(null=True, verbose_name='Comentarios TSU'),
        ),
        migrations.AddField(
            model_name='tituloelectronico',
            name='created_at_titulo_electronico',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tituloelectronico',
            name='curp_titulo_electronico',
            field=models.ImageField(null=True, upload_to='files/', verbose_name='CURP'),
        ),
        migrations.AddField(
            model_name='tituloelectronico',
            name='foto_infantil_bn_titulo_electronico',
            field=models.ImageField(null=True, upload_to='files/', verbose_name='Foto Infantil B/N'),
        ),
        migrations.AddField(
            model_name='tituloelectronico',
            name='foto_infantil_color_titulo_electronico',
            field=models.ImageField(null=True, upload_to='files/', verbose_name='Foto Infantil Color'),
        ),
        migrations.AddField(
            model_name='tituloelectronico',
            name='id_alumno_titulo_electronico',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.alumno'),
        ),
        migrations.AddField(
            model_name='tituloelectronico',
            name='status_acta_nacimiento_titulo_electronico',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tituloelectronico',
            name='status_certificado_bachiller_titulo_electronico',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tituloelectronico',
            name='status_curp_titulo_electronico',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tituloelectronico',
            name='status_foto_infantil_bn_titulo_electronico',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tituloelectronico',
            name='status_foto_infantil_color_titulo_electronico',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tituloelectronico',
            name='status_tsu_titulo_electronico',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tituloelectronico',
            name='tsu_titulo_electronico',
            field=models.ImageField(null=True, upload_to='files/', verbose_name='TSU'),
        ),
        migrations.AddField(
            model_name='tituloelectronico',
            name='updated_at_titulo_electronico',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
