# Generated by Django 3.2.13 on 2022-06-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20220624_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tituloelectronico',
            name='acta_nacimiento_titulo_electronico',
            field=models.FileField(null=True, upload_to='files/', verbose_name='Acta de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='certificado_bachiller_titulo_electronico',
            field=models.FileField(null=True, upload_to='files/', verbose_name='Certificado de Bachiller'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='curp_titulo_electronico',
            field=models.FileField(null=True, upload_to='files/', verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='foto_infantil_bn_titulo_electronico',
            field=models.FileField(null=True, upload_to='files/', verbose_name='Foto Infantil B/N'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='foto_infantil_color_titulo_electronico',
            field=models.FileField(null=True, upload_to='files/', verbose_name='Foto Infantil Color'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='tsu_titulo_electronico',
            field=models.FileField(null=True, upload_to='files/', verbose_name='TSU'),
        ),
    ]
