# Generated by Django 3.2.13 on 2022-06-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20220624_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tituloelectronico',
            name='comentarios_acta_nacimiento_titulo_electronico',
            field=models.TextField(default='Sin comemtarios', verbose_name='Comentarios Acta de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='comentarios_certificado_bachiller_titulo_electronico',
            field=models.TextField(default='Sin comemtarios', verbose_name='Comentarios Certificado de Bachiller'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='comentarios_curp_titulo_electronico',
            field=models.TextField(default='Sin comemtarios', verbose_name='Comentarios CURP'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='comentarios_foto_infantil_bn_titulo_electronico',
            field=models.TextField(default='Sin comemtarios', verbose_name='Comentarios Foto Infantil B/N'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='comentarios_foto_infantil_color_titulo_electronico',
            field=models.TextField(default='Sin comemtarios', verbose_name='Comentarios Foto Infantil Color'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='comentarios_tsu_titulo_electronico',
            field=models.TextField(default='Sin comemtarios', verbose_name='Comentarios TSU'),
        ),
    ]
