# Generated by Django 3.2.13 on 2022-06-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20220624_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tituloelectronico',
            name='status_acta_nacimiento_titulo_electronico',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='status_certificado_bachiller_titulo_electronico',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='status_curp_titulo_electronico',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='status_foto_infantil_bn_titulo_electronico',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='status_foto_infantil_color_titulo_electronico',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='status_tsu_titulo_electronico',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
