# Generated by Django 3.2.13 on 2022-06-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20220624_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tituloelectronico',
            name='acta_nacimiento_titulo_electronico',
            field=models.FileField(blank=True, upload_to='media/files6029beaf-d5ef-4a13-9f85-eb10d11c9c63', verbose_name='Acta de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='certificado_bachiller_titulo_electronico',
            field=models.FileField(blank=True, upload_to='media/files6029beaf-d5ef-4a13-9f85-eb10d11c9c63', verbose_name='Certificado de Bachiller'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='curp_titulo_electronico',
            field=models.FileField(blank=True, upload_to='media/files6029beaf-d5ef-4a13-9f85-eb10d11c9c63', verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='foto_infantil_bn_titulo_electronico',
            field=models.FileField(blank=True, upload_to='media/files6029beaf-d5ef-4a13-9f85-eb10d11c9c63', verbose_name='Foto Infantil B/N'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='foto_infantil_color_titulo_electronico',
            field=models.FileField(blank=True, upload_to='media/files6029beaf-d5ef-4a13-9f85-eb10d11c9c63', verbose_name='Foto Infantil Color'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='tsu_titulo_electronico',
            field=models.FileField(blank=True, upload_to='media/files6029beaf-d5ef-4a13-9f85-eb10d11c9c63', verbose_name='TSU'),
        ),
    ]
