# Generated by Django 3.2.13 on 2022-06-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20220624_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tituloelectronico',
            name='acta_nacimiento_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/737a7ff8-9cc3-4730-a35c-c52251d99cd6', verbose_name='Acta de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='certificado_bachiller_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/737a7ff8-9cc3-4730-a35c-c52251d99cd6', verbose_name='Certificado de Bachiller'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='curp_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/737a7ff8-9cc3-4730-a35c-c52251d99cd6', verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='foto_infantil_bn_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/737a7ff8-9cc3-4730-a35c-c52251d99cd6', verbose_name='Foto Infantil B/N'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='foto_infantil_color_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/737a7ff8-9cc3-4730-a35c-c52251d99cd6', verbose_name='Foto Infantil Color'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='tsu_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/737a7ff8-9cc3-4730-a35c-c52251d99cd6', verbose_name='TSU'),
        ),
    ]
