# Generated by Django 3.2.13 on 2022-06-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20220628_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='apellido_alumno',
        ),
        migrations.AddField(
            model_name='alumno',
            name='apellidom_alumno',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='alumno',
            name='apellidop_alumno',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='alumno',
            name='area_carrera_alumno',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='alumno',
            name='genero_alumno',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='acta_nacimiento_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/87833086-a001-406a-adf1-df3ca718d119', verbose_name='Acta de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='certificado_bachiller_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/87833086-a001-406a-adf1-df3ca718d119', verbose_name='Certificado de Bachiller'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='curp_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/87833086-a001-406a-adf1-df3ca718d119', verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='foto_infantil_bn_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/87833086-a001-406a-adf1-df3ca718d119', verbose_name='Foto Infantil B/N'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='foto_infantil_color_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/87833086-a001-406a-adf1-df3ca718d119', verbose_name='Foto Infantil Color'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='tsu_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/87833086-a001-406a-adf1-df3ca718d119', verbose_name='TSU'),
        ),
    ]
