# Generated by Django 3.2.13 on 2022-07-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20220629_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='matricula_alumno',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='matricula_empleado',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='acta_nacimiento_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/3f1d6d18-3fc0-4f24-8af1-e05a3b5f267c', verbose_name='Acta de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='certificado_bachiller_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/3f1d6d18-3fc0-4f24-8af1-e05a3b5f267c', verbose_name='Certificado de Bachiller'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='comentarios_acta_nacimiento_titulo_electronico',
            field=models.TextField(blank=True, default='Sin comentarios', verbose_name='Comentarios Acta de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='comentarios_certificado_bachiller_titulo_electronico',
            field=models.TextField(blank=True, default='Sin comentarios', verbose_name='Comentarios Certificado de Bachiller'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='comentarios_curp_titulo_electronico',
            field=models.TextField(blank=True, default='Sin comentarios', verbose_name='Comentarios CURP'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='comentarios_foto_infantil_bn_titulo_electronico',
            field=models.TextField(blank=True, default='Sin comentarios', verbose_name='Comentarios Foto Infantil B/N'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='comentarios_foto_infantil_color_titulo_electronico',
            field=models.TextField(blank=True, default='Sin comentarios', verbose_name='Comentarios Foto Infantil Color'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='comentarios_tsu_titulo_electronico',
            field=models.TextField(blank=True, default='Sin comentarios', verbose_name='Comentarios TSU'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='curp_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/3f1d6d18-3fc0-4f24-8af1-e05a3b5f267c', verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='foto_infantil_bn_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/3f1d6d18-3fc0-4f24-8af1-e05a3b5f267c', verbose_name='Foto Infantil B/N'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='foto_infantil_color_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/3f1d6d18-3fc0-4f24-8af1-e05a3b5f267c', verbose_name='Foto Infantil Color'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='tsu_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/3f1d6d18-3fc0-4f24-8af1-e05a3b5f267c', verbose_name='TSU'),
        ),
    ]
