# Generated by Django 3.2.13 on 2022-07-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20220701_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificadotitulacion',
            name='id_alumno_certificado_titulacion',
        ),
        migrations.RemoveField(
            model_name='certificadotitulacion',
            name='periodo_escolar_end_certificado_titulacion',
        ),
        migrations.RemoveField(
            model_name='certificadotitulacion',
            name='periodo_escolar_init_certificado_titulacion',
        ),
        migrations.RemoveField(
            model_name='certificadotitulacion',
            name='plan_estudio_certificado_titulacion',
        ),
        migrations.AddField(
            model_name='certificadotitulacion',
            name='anio_plan_estudios_titulacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certificadotitulacion',
            name='apellidom_alumno_titulacion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='certificadotitulacion',
            name='apellidop_alumno_titulacion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='certificadotitulacion',
            name='area_carrera_titulacion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='certificadotitulacion',
            name='carrera_titulacion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='certificadotitulacion',
            name='director_carrera_titulacion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='certificadotitulacion',
            name='jefe_area_servicios_escolares_titulacion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='certificadotitulacion',
            name='matricula_alumno_titulacion',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='certificadotitulacion',
            name='nombre_alumno_titulacion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='certificadotitulacion',
            name='periodo_escolar_end_titulacion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='certificadotitulacion',
            name='periodo_escolar_init_titulacion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='certificadotitulacion',
            name='tipo_carrera_titulacion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='acta_nacimiento_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/656b2f34-eca4-46eb-a944-9b845c06ef2f', verbose_name='Acta de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='certificado_bachiller_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/656b2f34-eca4-46eb-a944-9b845c06ef2f', verbose_name='Certificado de Bachiller'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='curp_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/656b2f34-eca4-46eb-a944-9b845c06ef2f', verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='foto_infantil_bn_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/656b2f34-eca4-46eb-a944-9b845c06ef2f', verbose_name='Foto Infantil B/N'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='foto_infantil_color_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/656b2f34-eca4-46eb-a944-9b845c06ef2f', verbose_name='Foto Infantil Color'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='tsu_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/656b2f34-eca4-46eb-a944-9b845c06ef2f', verbose_name='TSU'),
        ),
    ]
