# Generated by Django 3.2.13 on 2022-07-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20220705_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadotitulacion',
            name='calificaciones_titulacion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='acta_nacimiento_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/ecfbe722-e6b6-404e-8f8d-d93b7f000ce0', verbose_name='Acta de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='certificado_bachiller_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/ecfbe722-e6b6-404e-8f8d-d93b7f000ce0', verbose_name='Certificado de Bachiller'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='curp_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/ecfbe722-e6b6-404e-8f8d-d93b7f000ce0', verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='foto_infantil_bn_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/ecfbe722-e6b6-404e-8f8d-d93b7f000ce0', verbose_name='Foto Infantil B/N'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='foto_infantil_color_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/ecfbe722-e6b6-404e-8f8d-d93b7f000ce0', verbose_name='Foto Infantil Color'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='tsu_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/ecfbe722-e6b6-404e-8f8d-d93b7f000ce0', verbose_name='TSU'),
        ),
    ]
