# Generated by Django 3.2.13 on 2022-07-10 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20220709_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadotitulacion',
            name='matricula_alumno_titulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.alumno'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='acta_nacimiento_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/b7f9888f-3ee7-4be3-80a9-9712ead008bc', verbose_name='Acta de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='certificado_bachiller_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/b7f9888f-3ee7-4be3-80a9-9712ead008bc', verbose_name='Certificado de Bachiller'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='curp_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/b7f9888f-3ee7-4be3-80a9-9712ead008bc', verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='foto_infantil_bn_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/b7f9888f-3ee7-4be3-80a9-9712ead008bc', verbose_name='Foto Infantil B/N'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='foto_infantil_color_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/b7f9888f-3ee7-4be3-80a9-9712ead008bc', verbose_name='Foto Infantil Color'),
        ),
        migrations.AlterField(
            model_name='tituloelectronico',
            name='tsu_titulo_electronico',
            field=models.FileField(blank=True, upload_to='filesT/b7f9888f-3ee7-4be3-80a9-9712ead008bc', verbose_name='TSU'),
        ),
    ]
