# Generated by Django 3.2.13 on 2022-07-14 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0024_auto_20220710_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='degreeCertificate',
            fields=[
                ('id_degree_certificate', models.AutoField(primary_key=True, serialize=False)),
                ('name_student_degree', models.CharField(default='', max_length=50)),
                ('last_name_degree', models.CharField(default='', max_length=50)),
                ('second_last_name_degree', models.CharField(default='', max_length=50)),
                ('syllabus_year_degree', models.IntegerField(default=0)),
                ('start_school_term_degree', models.CharField(default='', max_length=50)),
                ('end_school_term_degree', models.CharField(default='', max_length=50)),
                ('career_degree', models.CharField(default='', max_length=50)),
                ('area_career_degree', models.CharField(default='', max_length=50)),
                ('type_career_degree', models.CharField(default='', max_length=50)),
                ('head_school_services_area_degree', models.CharField(default='', max_length=50)),
                ('director_career_degree', models.CharField(default='', max_length=50)),
                ('ratings_degree', models.TextField(default='')),
                ('created_at_degree', models.DateTimeField(auto_now_add=True)),
                ('updated_at_degree', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='electronicDegree',
            fields=[
                ('id_electronic_degree', models.AutoField(primary_key=True, serialize=False)),
                ('small_photo_bw_electronic_degree', models.FileField(blank=True, upload_to='filesT/463eabdc-7467-4329-9af6-4e84d46f21d9', verbose_name='Foto Infantil B/N')),
                ('small_photo_color_electronic_degree', models.FileField(blank=True, upload_to='filesT/463eabdc-7467-4329-9af6-4e84d46f21d9', verbose_name='Foto Infantil Color')),
                ('curp_electronic_degree', models.FileField(blank=True, upload_to='filesT/463eabdc-7467-4329-9af6-4e84d46f21d9', verbose_name='CURP')),
                ('birth_certificate_electronic_degree', models.FileField(blank=True, upload_to='filesT/463eabdc-7467-4329-9af6-4e84d46f21d9', verbose_name='Acta de Nacimiento')),
                ('high_school_certificate_electronic_degree', models.FileField(blank=True, upload_to='filesT/463eabdc-7467-4329-9af6-4e84d46f21d9', verbose_name='Certificado de Bachiller')),
                ('tsu_electronic_degree', models.FileField(blank=True, upload_to='filesT/463eabdc-7467-4329-9af6-4e84d46f21d9', verbose_name='TSU')),
                ('status_small_photo_bw_electronic_degree', models.BooleanField(blank=True, null=True)),
                ('status_small_photo_color_electronic_degree', models.BooleanField(blank=True, null=True)),
                ('status_curp_electronic_degree', models.BooleanField(blank=True, null=True)),
                ('status_birth_certificate_electronic_degree', models.BooleanField(blank=True, null=True)),
                ('status_high_school_certificate_electronic_degree', models.BooleanField(blank=True, null=True)),
                ('status_tsu_electronic_degree', models.BooleanField(blank=True, null=True)),
                ('comments_small_photo_bw_electronic_degree', models.TextField(blank=True, default='Sin comentarios', verbose_name='Comentarios Foto Infantil B/N')),
                ('comments_small_photo_color_electronic_degree', models.TextField(blank=True, default='Sin comentarios', verbose_name='Comentarios Foto Infantil Color')),
                ('comments_curp_electronic_degree', models.TextField(blank=True, default='Sin comentarios', verbose_name='Comentarios CURP')),
                ('comments_birth_certificate_electronic_degree', models.TextField(blank=True, default='Sin comentarios', verbose_name='Comentarios Acta de Nacimiento')),
                ('comments_high_school_certificate_electronic_degree', models.TextField(blank=True, default='Sin comentarios', verbose_name='Comentarios Certificado de Bachiller')),
                ('comments_tsu_electronic_degree', models.TextField(blank=True, default='Sin comentarios', verbose_name='Comentarios TSU')),
                ('created_at_electronic_degree', models.DateTimeField(auto_now_add=True)),
                ('updated_at_electronic_degree', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('enrollment_student', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name_student', models.CharField(max_length=50)),
                ('last_name_student', models.CharField(default='', max_length=50)),
                ('second_last_name_student', models.CharField(default='', max_length=50)),
                ('career_student', models.CharField(max_length=50)),
                ('area_career_student', models.CharField(default='', max_length=50)),
                ('gender_student', models.CharField(default='', max_length=50)),
                ('email_student', models.EmailField(max_length=50)),
                ('phone_student', models.CharField(max_length=50)),
                ('created_at_student', models.DateTimeField(auto_now_add=True)),
                ('updated_at_student', models.DateTimeField(auto_now=True)),
                ('estadiasTSU_student', models.BooleanField(default=False)),
                ('estadiasIngLic_student', models.BooleanField(default=False)),
                ('id_user_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='certificadotitulacion',
            name='matricula_alumno_titulacion',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='id_user_empleado',
        ),
        migrations.RemoveField(
            model_name='tituloelectronico',
            name='id_alumno_titulo_electronico',
        ),
        migrations.DeleteModel(
            name='alumno',
        ),
        migrations.DeleteModel(
            name='certificadoTitulacion',
        ),
        migrations.DeleteModel(
            name='empleado',
        ),
        migrations.DeleteModel(
            name='tituloElectronico',
        ),
        migrations.AddField(
            model_name='electronicdegree',
            name='id_alumno_electronic_degree_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.student'),
        ),
        migrations.AddField(
            model_name='degreecertificate',
            name='enrollment_student_degree_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student'),
        ),
    ]
