# Generated by Django 3.2.13 on 2022-07-14 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20220714_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronicdegree',
            name='id_alumno_electronic_degree',
        ),
        migrations.AddField(
            model_name='electronicdegree',
            name='id_student_electronic_degree',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.student'),
        ),
        migrations.AlterField(
            model_name='electronicdegree',
            name='birth_certificate_electronic_degree',
            field=models.FileField(blank=True, upload_to='filesT/3daeff5c-5178-40bf-8175-670ff25a4aa9', verbose_name='Acta de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='electronicdegree',
            name='curp_electronic_degree',
            field=models.FileField(blank=True, upload_to='filesT/3daeff5c-5178-40bf-8175-670ff25a4aa9', verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='electronicdegree',
            name='high_school_certificate_electronic_degree',
            field=models.FileField(blank=True, upload_to='filesT/3daeff5c-5178-40bf-8175-670ff25a4aa9', verbose_name='Certificado de Bachiller'),
        ),
        migrations.AlterField(
            model_name='electronicdegree',
            name='small_photo_bw_electronic_degree',
            field=models.FileField(blank=True, upload_to='filesT/3daeff5c-5178-40bf-8175-670ff25a4aa9', verbose_name='Foto Infantil B/N'),
        ),
        migrations.AlterField(
            model_name='electronicdegree',
            name='small_photo_color_electronic_degree',
            field=models.FileField(blank=True, upload_to='filesT/3daeff5c-5178-40bf-8175-670ff25a4aa9', verbose_name='Foto Infantil Color'),
        ),
        migrations.AlterField(
            model_name='electronicdegree',
            name='tsu_electronic_degree',
            field=models.FileField(blank=True, upload_to='filesT/3daeff5c-5178-40bf-8175-670ff25a4aa9', verbose_name='TSU'),
        ),
    ]
