# Generated by Django 3.2.13 on 2022-07-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20220714_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicdegree',
            name='birth_certificate_electronic_degree',
            field=models.FileField(blank=True, upload_to='filesT/b9622b36-c55d-4522-8843-42bf0829b240', verbose_name='Acta de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='electronicdegree',
            name='curp_electronic_degree',
            field=models.FileField(blank=True, upload_to='filesT/b9622b36-c55d-4522-8843-42bf0829b240', verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='electronicdegree',
            name='high_school_certificate_electronic_degree',
            field=models.FileField(blank=True, upload_to='filesT/b9622b36-c55d-4522-8843-42bf0829b240', verbose_name='Certificado de Bachiller'),
        ),
        migrations.AlterField(
            model_name='electronicdegree',
            name='small_photo_bw_electronic_degree',
            field=models.FileField(blank=True, upload_to='filesT/b9622b36-c55d-4522-8843-42bf0829b240', verbose_name='Foto Infantil B/N'),
        ),
        migrations.AlterField(
            model_name='electronicdegree',
            name='small_photo_color_electronic_degree',
            field=models.FileField(blank=True, upload_to='filesT/b9622b36-c55d-4522-8843-42bf0829b240', verbose_name='Foto Infantil Color'),
        ),
        migrations.AlterField(
            model_name='electronicdegree',
            name='tsu_electronic_degree',
            field=models.FileField(blank=True, upload_to='filesT/b9622b36-c55d-4522-8843-42bf0829b240', verbose_name='TSU'),
        ),
        migrations.AlterField(
            model_name='student',
            name='area_career_student',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
