# Generated by Django 3.2.13 on 2023-07-07 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0029_auto_20220714_1950'),
    ]

    operations = [
        migrations.DeleteModel(
            name='estadisticasTitulacion',
        ),
        migrations.AlterModelOptions(
            name='degreecertificate',
            options={'verbose_name': 'Certificado de titulacion', 'verbose_name_plural': 'Certificados de titulacion'},
        ),
        migrations.AlterModelOptions(
            name='electronicdegree',
            options={'verbose_name': 'Titulo electronico', 'verbose_name_plural': 'Titulos electronico'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['enrollment_student'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterField(
            model_name='degreecertificate',
            name='area_career_degree',
            field=models.CharField(default='', max_length=50, verbose_name='area de la carrera'),
        ),
        migrations.AlterField(
            model_name='degreecertificate',
            name='career_degree',
            field=models.CharField(default='', max_length=50, verbose_name='carrera'),
        ),
        migrations.AlterField(
            model_name='degreecertificate',
            name='created_at_degree',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='degreecertificate',
            name='director_career_degree',
            field=models.CharField(default='', max_length=50, verbose_name='director de la carrera'),
        ),
        migrations.AlterField(
            model_name='degreecertificate',
            name='end_school_term_degree',
            field=models.CharField(default='', max_length=50, verbose_name='fin del periodo escolar'),
        ),
        migrations.AlterField(
            model_name='degreecertificate',
            name='enrollment_student_degree',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.student', verbose_name='matricula del estudiante'),
        ),
        migrations.AlterField(
            model_name='degreecertificate',
            name='head_school_services_area_degree',
            field=models.CharField(default='', max_length=50, verbose_name='encargado de area de servicios escolares'),
        ),
        migrations.AlterField(
            model_name='degreecertificate',
            name='id_degree_certificate',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id del certificado'),
        ),
        migrations.AlterField(
            model_name='degreecertificate',
            name='last_name_degree',
            field=models.CharField(default='', max_length=50, verbose_name='apellido paterno'),
        ),
        migrations.AlterField(
            model_name='degreecertificate',
            name='name_student_degree',
            field=models.CharField(default='', max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='degreecertificate',
            name='ratings_degree',
            field=models.TextField(default='', verbose_name='calificaciones'),
        ),
        migrations.AlterField(
            model_name='degreecertificate',
            name='second_last_name_degree',
            field=models.CharField(default='', max_length=50, verbose_name='apellido materno'),
        ),
        migrations.AlterField(
            model_name='degreecertificate',
            name='start_school_term_degree',
            field=models.CharField(default='', max_length=50, verbose_name='inicio del periodo escolar'),
        ),
        migrations.AlterField(
            model_name='degreecertificate',
            name='syllabus_year_degree',
            field=models.IntegerField(default=0, verbose_name='plan de estudios'),
        ),
        migrations.AlterField(
            model_name='degreecertificate',
            name='type_career_degree',
            field=models.CharField(default='', max_length=50, verbose_name='tipo de carrera'),
        ),
        migrations.AlterField(
            model_name='degreecertificate',
            name='updated_at_degree',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='electronicdegree',
            name='birth_certificate_electronic_degree',
            field=models.FileField(blank=True, upload_to='filesT/24341e04-bc54-4a4c-81fc-7cdd8d1792ee', verbose_name='Acta de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='electronicdegree',
            name='curp_electronic_degree',
            field=models.FileField(blank=True, upload_to='filesT/24341e04-bc54-4a4c-81fc-7cdd8d1792ee', verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='electronicdegree',
            name='high_school_certificate_electronic_degree',
            field=models.FileField(blank=True, upload_to='filesT/24341e04-bc54-4a4c-81fc-7cdd8d1792ee', verbose_name='Certificado de Bachiller'),
        ),
        migrations.AlterField(
            model_name='electronicdegree',
            name='id_electronic_degree',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id del titulo'),
        ),
        migrations.AlterField(
            model_name='electronicdegree',
            name='id_student_electronic_degree',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.student', verbose_name='matricula del estudiante'),
        ),
        migrations.AlterField(
            model_name='electronicdegree',
            name='small_photo_bw_electronic_degree',
            field=models.FileField(blank=True, upload_to='filesT/24341e04-bc54-4a4c-81fc-7cdd8d1792ee', verbose_name='Foto Infantil B/N'),
        ),
        migrations.AlterField(
            model_name='electronicdegree',
            name='small_photo_color_electronic_degree',
            field=models.FileField(blank=True, upload_to='filesT/24341e04-bc54-4a4c-81fc-7cdd8d1792ee', verbose_name='Foto Infantil Color'),
        ),
        migrations.AlterField(
            model_name='electronicdegree',
            name='status_birth_certificate_electronic_degree',
            field=models.BooleanField(blank=True, null=True, verbose_name='estatus del acta de nacimiento'),
        ),
        migrations.AlterField(
            model_name='electronicdegree',
            name='status_curp_electronic_degree',
            field=models.BooleanField(blank=True, null=True, verbose_name='estatus del curp'),
        ),
        migrations.AlterField(
            model_name='electronicdegree',
            name='status_high_school_certificate_electronic_degree',
            field=models.BooleanField(blank=True, null=True, verbose_name='estatus del certificado de bachiller'),
        ),
        migrations.AlterField(
            model_name='electronicdegree',
            name='status_small_photo_bw_electronic_degree',
            field=models.BooleanField(blank=True, null=True, verbose_name='estatus de la foto b/n'),
        ),
        migrations.AlterField(
            model_name='electronicdegree',
            name='status_small_photo_color_electronic_degree',
            field=models.BooleanField(blank=True, null=True, verbose_name='estatus de la foto a color'),
        ),
        migrations.AlterField(
            model_name='electronicdegree',
            name='status_tsu_electronic_degree',
            field=models.BooleanField(blank=True, null=True, verbose_name='estatus del certificado del TSU'),
        ),
        migrations.AlterField(
            model_name='electronicdegree',
            name='tsu_electronic_degree',
            field=models.FileField(blank=True, upload_to='filesT/24341e04-bc54-4a4c-81fc-7cdd8d1792ee', verbose_name='TSU'),
        ),
        migrations.AlterField(
            model_name='student',
            name='area_career_student',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='area de la carrera'),
        ),
        migrations.AlterField(
            model_name='student',
            name='career_student',
            field=models.CharField(max_length=50, verbose_name='carrera'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at_student',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email_student',
            field=models.EmailField(max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_student',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='matricula'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender_student',
            field=models.CharField(default='', max_length=50, verbose_name='genero'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_user_student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id user'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name_student',
            field=models.CharField(default='', max_length=50, verbose_name='apellido paterno'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name_student',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_student',
            field=models.CharField(max_length=50, verbose_name='tel'),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_last_name_student',
            field=models.CharField(default='', max_length=50, verbose_name='apellido materno'),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at_student',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado'),
        ),
    ]
